# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-14 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180714_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
