# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-07-14 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_trainer_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
