# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-07-14 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20180714_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
