# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-14 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0004_auto_20180714_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(default=None)),
                ('end_date', models.DateTimeField(default=None)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Trainer')),
                ('users', models.ManyToManyField(to='profiles.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_link', models.URLField(default=None, null=True)),
                ('level', models.CharField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=1, max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='workouts',
            field=models.ManyToManyField(to='workouts.Workout'),
        ),
    ]
