# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-07-15 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20180715_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='back_ground_image',
            field=models.URLField(default=None, null=True),
        ),
    ]
