# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-07-15 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_trainingsession_back_ground_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='end_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='start_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
