# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-07-15 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_auto_20180715_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsession',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Trainer'),
        ),
    ]
